version: "2"

services:
  acntech_zookeeper_exhibitor:
    build: .
    image: acntech/zookeeper-exhibitor:latest
    container_name: acntech-zookeeper-exhibitor
    hostname: zk01
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=zk01
      - ZOO_LOG4J_PROP=INFO,CONSOLE,ROLLINGFILE
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "8080:8080"