version: "2"

services:
  zk01:
    image: acntech/zookeeper-exhibitor:latest
    hostname: zk01
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=zk01,zk02,zk03,zk04,zk05
      - ZOO_LOG4J_PROP=INFO,CONSOLE,ROLLINGFILE
    ports:
      - "8081:8080"
  zk02:
    image: acntech/zookeeper-exhibitor:latest
    hostname: zk02
    environment:
      - ZOOKEEPER_ID=2
      - ZOOKEEPER_HOSTS=zk01,zk02,zk03,zk04,zk05
      - ZOO_LOG4J_PROP=INFO,CONSOLE,ROLLINGFILE
    ports:
      - "8082:8080"
  zk03:
    image: acntech/zookeeper-exhibitor:latest
    hostname: zk03
    environment:
      - ZOOKEEPER_ID=3
      - ZOOKEEPER_HOSTS=zk01,zk02,zk03,zk04,zk05
      - ZOO_LOG4J_PROP=INFO,CONSOLE,ROLLINGFILE
    ports:
      - "8083:8080"
  zk04:
    image: acntech/zookeeper-exhibitor:latest
    hostname: zk04
    environment:
      - ZOOKEEPER_ID=4
      - ZOOKEEPER_HOSTS=zk01,zk02,zk03,zk04,zk05
      - ZOO_LOG4J_PROP=INFO,CONSOLE,ROLLINGFILE
    ports:
      - "8084:8080"
  zk05:
    image: acntech/zookeeper-exhibitor:latest
    hostname: zk05
    environment:
      - ZOOKEEPER_ID=5
      - ZOOKEEPER_HOSTS=zk01,zk02,zk03,zk04,zk05
      - ZOO_LOG4J_PROP=INFO,CONSOLE,ROLLINGFILE
    ports:
      - "8085:8080"